version: "3.2"
services:
  db:
    image: postgres:12
    volumes:
      - pg-vol:/var/lib/postgresql/data/
      - ./backend/dbbackup:/dbbackup
    env_file:
      - ./backend/pg_settings.env
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pg-vol: